[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["python"]
aptPkgs = ["pandoc"]

[deploy]
startCommand = "python web_app.py --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
